# Generated by Django 4.0 on 2021-12-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phonenumber', models.TextField(blank=True, max_length=10, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('home_location', models.CharField(max_length=30)),
                ('office_location', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
