# Generated by Django 4.0 on 2021-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxa_app', '0008_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
